### ISSUE TITLE
Issues integrating with DestinyItemManager

### ISSUE THREAD

**Issue by bhollis** [merceyz/babel-plugin-optimize-clsx#15]
I tried this out for DIM in https://github.com/DestinyItemManager/DIM/pull/4225 but ended up having to roll back because we saw the list of classes for some of our components getting collapsed into nothing. I tried writing a test in this repo that matched what we were doing, but it worked there. So it must have been something about our particular setup, either with babel/webpack caching or something else.

The code that was getting messed up looked like this:

```js
classNames('store-cell', 'account-wide', `bucket-${bucket.id}`);
```

I think if I remember right this was getting transformed into the string "bucket-".

I'm not sure if there were other parts that were getting broken. It had looked fine when running in the development server, but after I had to roll back I noticed that if I was running in the dev server it would render fine on the first pass, but if I hot-reloaded a file then it would start deleting my classes.

**Comment by merceyz** [comment]
Thanks for taking the time to test the plugin and report your findings!

The issue is that when `combine-strings` creates a new `TemplateElement` it doesn't provide the `cooked` value which causes `@babel/plugin-transform-template-literals` to convert it to 
```javascript
"".concat(bucket.id)
```

If you wouldn't mind testing again and report back that would be great

**Comment by bhollis** [comment]
Thank you! It looks like it works great now. Please let me know when you've cut a new release.

**Comment by merceyz** [comment]
Fantastic, v2.5.0 has been released
