### ISSUE TITLE
Support JSX props

### ISSUE THREAD

**Issue by mattcompiles** [merceyz/babel-plugin-optimize-clsx#17]
Hey 👋 

Was wondering if you'd be interested in supporting JSX props as valid targets for optimisation? Our component library uses the `clsx` API for it's `className` prop and would be a valid target for optimisation. 

e.g.
```
<Box className={{
  [classes.disabled]: disabled,
  [classes.focusVisible]: focusVisible && !disabled,
}} />

// Transforms to

<Box className={[disabled && classes.disabled, focusVisible && !disabled && classes.focusVisible]} />
```

Understand this is a slightly different scenario but still relevant.

**Comment by merceyz** [comment]
Hello,

Sure, sounds like a perfectly reasonable target for optimization. Is this something you'd be willing to implement?

**Comment by mattcompiles** [comment]
I'll try find some time to have a crack 👍

**Comment by merceyz** [comment]
@mattsjones If you don't have time I can take care of it, I have some ideas on how this could be done.

---

@oliviertassinari @eps1lon what is the likelyhood that Material-UI will continue to have all components run their `className` run through `clsx`? Could make Material-UI a default target for this optimization.

**Comment by oliviertassinari** [comment]
@merceyz The last iteration I had on an unstyled version of the Material-UI components was using the following:

**cxFactory.js**
```js
import capitalize from './capitalize';

export default function cxFactory(classes, name) {
  return (key1, key2) => {
    if (classes && classes[key1]) {
      return classes[key1];
    }
    return `${name}-${key1}${key2 ? capitalize(key2) : ''}`;
  };
}
```

**Component.unstyled.js**
```jsx
  const cx = cxFactory(classes, 'MuiTableCell');

  return (
    <Component
      ref={ref}
      {...passProps('root', { variant, table, align, padding, size, as })}
      className={clsx(
      className={clsx(
        cx('root'),
        {
          [cx('head')]: variant === 'head',
          [cx('stickyHeader')]: variant === 'head' && table && table.stickyHeader,
          [cx('body')]: variant === 'body',
          [cx('footer')]: variant === 'footer',
          [cx('align', align)]: align !== 'inherit',
          [cx('padding', padding)]: padding !== 'default',
          [cx('size', size)]: size !== 'medium',
        },
        className,
      )}
```

But it was just an experiment, in which we still rely on clsx. Unless we come up with a solution that doesn't require to merge classnames, not like above, I believe we will keep using `clsx`? What other concern do you have in mind, that we switch back to `classnames` (I doubt it)?
`clsx` seems to start to grow outside of Material-UI, which is great, I hope it will become a standard in the React community.

**Comment by merceyz** [comment]
> What other concern do you have in mind

I was planning on having material-ui components be a target of this optimization by default, but for that to happen the `className` prop of all the components must always be passed to something like `clsx`. This makes this project depend on the internals of material-ui though so I scrapped that rather quickly.
