### ISSUE TITLE
Incorrect handling of object expressions combined with other arguments

### ISSUE THREAD

**Issue by dfernandez-asapp** [merceyz/babel-plugin-optimize-clsx#18]
# Input:
```
clsx(a, b, { [foo]: bar }, c);
```
# Output:
```
clsx(a, b, c, bar && foo)
```
# Problem
In the generated call, when bar is true, the expression results in `clsx(a, b, c, foo)` it should be `clsx(a,b,foo,c)`.

The order of classes th in the class attribute matters: https://codepen.io/dfernandez-asapp/pen/mdJBQOX

**Comment by eps1lon** [comment]
> The order of classes th in the class attribute matters: codepen.io/dfernandez-asapp/pen/mdJBQOX

I cannot reproduce this. The color is the same for `<div class="second first">Test</div>` and `<div class="first second">Test</div>`. Which browser/OS are you using?

**Comment by dfernandez-asapp** [comment]
@eps1lon thanks for looking into the issue, your clarification helped in my confusion.

I'm going to close this, since is a non-issue.
