### ISSUE TITLE
Add obj-str and classcat to default libraries

### ISSUE THREAD

**Issue by minushabens** [merceyz/babel-plugin-optimize-clsx#19]
Thanks for your amazing work here!

I think we should add [obj-str](https://github.com/lukeed/obj-str) and [classcat](https://github.com/jorgebucaran/classcat) to default libraries.

`obj-str`'s author is the same of `clsx`: @lukeed.

I will ask them to link to this project in their Readme.

**Comment by merceyz** [comment]
Neither of those support variadic arguments so their API isn't compatible with the output of this plugin
